ptti/urls.py
from django.conf.urls import url

from . import views

app_name = 'ptti'
urlpatterns = [
    url(r'^$', views.login, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^password/$', views.reset_password, name='reset_password'),
    url(r'^password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',views.reset_password_confirm, name='reset_password_confirm'),

    url(r'^perfil/$', views.perfil, name='perfil'),
    url(r'^perfil/editar/(?P<user_id>[0-9]+)$',views.perfil_editar, name='perfil_editar'),
    url(r'^perfil/contrasena/(?P<user_id>[0-9]+)$', views.perfil_cambiar_contrasena, name='perfil_cambiar_contrasena'),

    url(r'^usuarios/$',views.usuarios, name='usuarios'),
    url(r'^usuarios/crear$',views.crear_usuario, name='crear_usuario'),
    url(r'^usuarios/editar/(?P<user_id>[0-9]+)$',views.editar_usuario, name='editar_usuario'),
    url(r'^usuarios/activar/(?P<user_id>[0-9]+)$',views.activar_usuario, name='activar_usuario'),
    url(r'^usuarios/desactivar/(?P<user_id>[0-9]+)$',views.desactivar_usuario, name='desactivar_usuario'),

    url(r'^administradores/$',views.administradores, name='administradores'),
    url(r'^administradores/crear$',views.crear_administrador, name='crear_administrador'),
    url(r'^administradores/editar/(?P<user_id>[0-9]+)$',views.editar_administrador, name='editar_administrador'),
    url(r'^administradores/activar/(?P<user_id>[0-9]+)$',views.activar_administrador, name='activar_administrador'),
    url(r'^administradores/desactivar/(?P<user_id>[0-9]+)$',views.desactivar_administrador, name='desactivar_administrador'),

    url(r'^psicologos/$',views.psicologos, name='psicologos'),
    url(r'^psicologos/crear$',views.crear_psicologo, name='crear_psicologo'),
    url(r'^psicologos/editar/(?P<user_id>[0-9]+)$',views.editar_psicologo, name='editar_psicologo'),
    url(r'^psicologos/activar/(?P<user_id>[0-9]+)$',views.activar_psicologo, name='activar_psicologo'),
    url(r'^psicologos/desactivar/(?P<user_id>[0-9]+)$',views.desactivar_psicologo, name='desactivar_psicologo'),
    url(r'^psicologos/asignar_psicologo_grupo/(?P<user_id>[0-9]+)$',views.asignar_psicologo_grupo, name='asignar_psicologo_grupo'),

    url(r'^estudiantes/$',views.estudiantes, name='estudiantes'),
    url(r'^estudiantes/crear$',views.crear_estudiante, name='crear_estudiante'),
    url(r'^estudiantes/editar/(?P<user_id>[0-9]+)$',views.editar_estudiante, name='editar_estudiante'),
    url(r'^estudiantes/activar/(?P<user_id>[0-9]+)$',views.activar_estudiante, name='activar_estudiante'),
    url(r'^estudiantes/desactivar/(?P<user_id>[0-9]+)$',views.desactivar_estudiante, name='desactivar_estudiante'),

    url(r'^instituciones/$',views.instituciones, name='instituciones'),
    url(r'^instituciones/crear$',views.crear_institucion, name='crear_institucion'),
    url(r'^instituciones/editar/(?P<ins_id>[0-9]+)$',views.editar_institucion, name='editar_institucion'),
    url(r'^instituciones/activar/(?P<ins_id>[0-9]+)$',views.activar_institucion, name='activar_institucion'),
    url(r'^instituciones/desactivar/(?P<ins_id>[0-9]+)$',views.desactivar_institucion, name='desactivar_institucion'),

    url(r'^grupos/$',views.grupos, name='grupos'),
    url(r'^grupos/crear$',views.crear_grupo, name='crear_grupo'),
    url(r'^grupos/editar/(?P<gru_id>[0-9]+)$',views.editar_grupo, name='editar_grupo'),
    url(r'^grupos/activar/(?P<gru_id>[0-9]+)$',views.activar_grupo, name='activar_grupo'),
    url(r'^grupos/desactivar/(?P<gru_id>[0-9]+)$',views.desactivar_grupo, name='desactivar_grupo'),
    url(r'^grupos/asignar_grupo_psicologo/(?P<gru_id>[0-9]+)$',views.asignar_grupo_psicologo, name='asignar_grupo_psicologo'),

    url(r'^test/$',views.testTI, name='test'),
    url(r'^test/crear$',views.crear_test, name='crear_test'),
    url(r'^test/cambiar_nombre/(?P<test_id>[0-9]+)$',views.cambiar_nombre_test, name='cambiar_nombre_test'),
    url(r'^test/activar/(?P<test_id>[0-9]+)$',views.activar_test, name='activar_test'),
    url(r'^test/desactivar/(?P<test_id>[0-9]+)$',views.desactivar_test, name='desactivar_test'),

    url(r'^test/preguntas/(?P<test_id>[0-9]+)$',views.preguntas_test, name='preguntas_test'),
    url(r'^test/preguntas/crear_pregunta/(?P<test_id>[0-9]+)$',views.crear_pregunta, name='crear_pregunta'),
    url(r'^test/preguntas/editar_pregunta/(?P<pre_id>[0-9]+)/(?P<test_id>[0-9]+)/$',views.editar_pregunta, name='editar_pregunta'),

    url(r'^test/preguntas/respuesta/(?P<pre_id>[0-9]+)$',views.respuestas_pregunta, name='respuestas_pregunta'),
    url(r'^test/preguntas/respuesta/crear_respuesta/(?P<pre_id>[0-9]+)$',views.crear_respuesta, name='crear_respuesta'),
    url(r'^test/preguntas/respuesta/editar_respuesta/(?P<res_id>[0-9]+)/(?P<pre_id>[0-9]+)/$',views.editar_respuesta, name='editar_respuesta'),

    #urls del psicologo

    url(r'^asignados/$',views.TestAsignados, name='TestAsignados'),
    #url(r'^asignados/asignarTestEstudiante/(?P<user_id>[0-9]+)/$',views.asignarTestEstudiante, name='asignarTestEstudiante'),
    url(r'^asignados/asignarTestEstudiante/$',views.asignarTestEstudiante, name='asignarTestEstudiante'),
    url(r'^asignados/asignarTestGrupo/$',views.asignarTestGrupo, name='asignarTestGrupo'),
    url(r'^asignados/asignarTestGrupo/listaEstudiantes/(?P<gru_id>[0-9]+)$',views.listaEstudiantes, name='listaEstudiantes'),

    #url(r'^asignados/asignarTestGrupo/(?P<user_id>[0-9]+)/$',views.asignarTestGrupo, name='asignarTestGrupo'),


    #url(r'^diagnosticar/$',views.diagnosticar, name='diganosticar'),



    #urls del estudiante
    #url(r'^/$',views.TestAsignados, name='TestAsignados'),

    #ulrs estudiante
    url(r'^mis-test/$',views.TestEstudiante, name='TestEstudiante'),
    url(r'^mis-test/(?P<id_test_asi>[0-9]+)$',views.IniciarTest, name='IniciarTest'),
    url(r'^mis-test/(?P<id_test_asi>[0-9]+)/responder/(?P<no_preg>[0-9]+)$',views.ResponderTest, name='ResponderTest'),
    url(r'^mis-test/(?P<id_test_asi>[0-9]+)/terminar$',views.TerminarTest, name='TerminarTest'),
    url(r'^mis-test/respuestas/(?P<id_test_asi>[0-9]+)$',views.RespuestasTest, name='RespuestasTest'),
]

templates/asignar_form.html
{% extends 'base.html' %}

{% block titulo %}
	Nueva asignacion
{% endblock %}

{% block encabezado %}
	<h1>asigna un test</h1>
{% endblock %}

{% block menu %}

{% endblock %}

{% block contenido %}
	<form id='formulario' method='post' action=''>
		{% csrf_token %}
		<table>{{formulario}}</table>
		<p><input class="btn btn-primary" type='submit' value='Guardar'/></p>
		
	</form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang='es'>
  <head>
    <meta charset='utf-8'>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>PTTI - {% block titulo %}{% endblock %}</title>
    <!-- Latest compiled and minified CSS -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> -->
    <!-- Optional theme -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->

    {% load static %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="{% static "ptti/css/bootstrap.min.css" %}" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="{% static "ptti/css/bootstrap-theme.min.css" %}" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    {% block style_css %}{% endblock %}
  </head>

  <body>


    	<nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"><b>PTTI</b></a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">

        		  {% if request.user.is_anonymous %}
              <ul class="nav navbar-nav navbar-right">
                <li><a href='/login'>Login</a></li>
              </ul>
              {% else %}
              <ul class="nav navbar-nav navbar-left">

                {% block menu %}{% endblock %}
                {% if request.user.is_superuser  %}
                  <!-- <li><a href='/usuarios/'>Usuarios</a></li> -->
                  <li><a href='/administradores/'>Administradores</a></li>
                {% endif %}

                {% if request.user.is_administrador %}
                  <li><a href='/psicologos/'>Psicologos</a></li>
                  <li><a href='/estudiantes/'>Estudiantes</a></li>
                  <li><a href='/instituciones/'>Instituciones</a></li>
                  <li><a href='/grupos/'>Grupos</a></li>
                  <li><a href='/test/'>Evaluaciones</a></li>
                {% endif %}

                {% if request.user.is_psicologo %}
                  <li><a href='/asignados/'>Asignar</a></li>
                  <li><a href='/diagnosticar/'>Diagnosticar</a></li>
                {% endif %}

                {% if request.user.is_estudiante %}
                  <li><a href='/mis-test/'>Mis Test</a></li>

                {% endif %}

              </ul>
              <ul class="nav navbar-nav navbar-right">
                <li><a href='/perfil'><b>{{ request.user.username|upper }}</b> Perfil</a></li>
                <li><a href='/logout'>Logout</a></li>
              </ul>
              {% endif %}

          </div>
        </div>
    	</nav>

    <div class="container col-12" style="margin-top:50px">
      {% block encabezado %}{% endblock %}
    	<hr />
  	  {% block contenido %}{% endblock %}
      <footer class="footer" style="padding-top: 40px;padding-bottom: 40px;margin-top: 40px;border-top: 2px solid #eee;">
    	   <p style="text-align:center">© 2016. Proyecto PTTI. Yenifer Rivas - Esteban Idarraga - Cristian Vazquez - Carlos Gutierrez</p>
      </footer>
    </div>

    <!-- Placed at the end of the document so the pages load faster -->
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script> -->
    <!-- Latest compiled and minified JavaScript -->
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script> -->

    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static "ptti/js/jquery.min.js" %}"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="{% static "ptti/js/bootstrap.min.js" %}" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


  </body>
</html>

templates/diagnosticar.html
diagnosticar

templates/error_usuario.html
{% extends 'base.html' %}

{% block titulo %}
	Error de acceso
{% endblock %}

{% block encabezado %}
	<h1>Error de acceso</h1>
{% endblock %}

{% block menu %}
{% endblock %}

{% block contenido %}
	<p>El usuario y la contraseña no coinciden o no existen.</p>
	<p>Intentalo de nuevo.</p>
	<form id='formulario' method='post' action=''>{% csrf_token %}
		<table>{{formulario}}</table>
		<p><input type='submit' value='Ingresar'/></p>
	</form>
{% endblock %}

templates/grupos.html
{% extends 'base.html' %}

{% block titulo %}
	Grupos
{% endblock %}

{% block encabezado %}
	<h1>Lista de grupos</h1>
{% endblock %}

{% block menu %}
{% endblock %}

{% block contenido %}
	<a class="btn btn-primary" href='crear'>Crear grupo</a>
  {% if grupos_lista %}
	<div class="table-responsive">
		<table class="table table-striped">
      <thead>
        <tr style="font-weight:bold;text-align:center">
					<td></td>
          <td>institucion</td>
          <td>jornada</td>
          <td>grado</td>
          <td>nombre</td>
					<td>psicologo</td>
          <td>opciones</td>
        </tr>
      </thead>
      <tbody>
				{% for grupo in grupos_lista %}
          <tr style="text-align:center">
						<td>{{ forloop.counter }}</td>
            <td><a href="{% url 'ptti:editar_grupo' grupo.id %}">{{ grupo.institucion }}</a></td>
						<td>{{ grupo.jornada }}</td>
            <td>{{ grupo.grado }}</td>
						<td>{{ grupo.nombre }}</td>
						<td>

						{% if grupo.psicologo %}
							{{ grupo.psicologo }}
						{% else %}
							<a class="btn btn-sm btn-success" href="{% url 'ptti:asignar_grupo_psicologo' grupo.id %}">Asignar psicologo</a>
						{% endif %}

						</td>
						<td>
							<a class="btn btn-sm btn-default" href="{% url 'ptti:editar_grupo' grupo.id %}">Editar</a>
							{% if grupo.is_active %}
								<a class="btn btn-sm btn-danger" href="{% url 'ptti:desactivar_grupo' grupo.id %}">Desactivar</a>
							{% else %}
						    <a class="btn btn-sm btn-success" href="{% url 'ptti:activar_grupo' grupo.id %}">Activar</a>
						  {% endif %}
						</td>
          </tr>
				{% endfor %}
      </tbody>
    </table>
	</div>

  {% else %}
		<div class="alert alert-danger" role="alert">
    	<p>No grupos</p>
		</div>
  {% endif %}
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block titulo %}Inicio{% endblock %}

{% block encabezado %}
	<h1>Inicio</h1>
{% endblock %}

{% block menu %}
{% endblock %}

{% block contenido %}
{% endblock %}

templates/ingresar.html
{% extends 'base.html' %}

{% block titulo %}
	Ingresa al sistema
{% endblock %}

{% block encabezado %}
	<h1>Bievenido a PTTI</h1>
{% endblock %}

{% block menu %}
{% endblock %}

{% block contenido %}
	<form id='formulario' method='post' action=''>{% csrf_token %}
		<table>{{formulario}}</table>
		<p><input type='submit' value='Ingresar'/></p>
	</form>
{% endblock %}

templates/instituciones.html
{% extends 'base.html' %}

{% block titulo %}
	Instituciones
{% endblock %}

{% block encabezado %}
	<h1>Lista de instituciones</h1>
{% endblock %}

{% block menu %}
{% endblock %}

{% block contenido %}
	<a class="btn btn-primary" href='crear'>Crear institucion</a>

	{% if instituciones_lista %}
	<div class="table-responsive">
		<table class="table table-striped">
      <thead>
        <tr style="font-weight:bold;text-align:center">
					<td></td>
          <td>nit</td>
          <td>nombre</td>
          <td>direccion</td>
          <td>telefono</td>
          <td>ciudad</td>
					<td>web</td>
					<td>opciones</td>
        </tr>
      </thead>
      <tbody>
				{% for institucion in instituciones_lista %}
          <tr style="text-align:center">
						<td>{{ forloop.counter }}</td>
            <td><a href="{% url 'ptti:editar_institucion' institucion.id %}">{{ institucion.nit }}</a></td>
						<td>{{ institucion.nombre }}</td>
            <td>{{ institucion.direccion }}</td>
						<td>{{ institucion.telefono }}</td>
						<td>{{ institucion.ciudad }}</td>
						<td>{{ institucion.web }}</td>
						<td>
							<a class="btn btn-sm btn-default" href="{% url 'ptti:editar_institucion' institucion.id %}">editar</a>
							{% if institucion.is_active %}
								<a class="btn btn-sm btn-danger" href="{% url 'ptti:desactivar_institucion' institucion.id %}">desactivar</a>
							{% else %}
						    <a class="btn btn-sm btn-success" href="{% url 'ptti:activar_institucion' institucion.id %}">activar</a>
						  {% endif %}
						</td>
          </tr>
				{% endfor %}
      </tbody>
    </table>
	</div>

  {% else %}
			<div class="alert alert-danger" role="alert">
      	<p>No instituciones</p>
			</div>
  {% endif %}

{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block titulo %}
	Ingresa al sistema
{% endblock %}

{% block encabezado %}
	<h1>Bievenido a PTTI</h1>
{% endblock %}

{% block menu %}
{% endblock %}

{% block contenido %}
<div class="container">

	<form class="form-signin" id='formulario' method='post' style="margin: 0 auto;max-width:330px;padding:15px;">
		{% csrf_token %}
		<table>{{formulario}}</table>
		<a href="{% url 'ptti:reset_password' %}">¿Olvidaste la contrase&ntilde;a?</a>
		<input class="btn btn-lg btn-primary btn-block" type='submit' value='Ingresar'/>


	</form>
</div>
{% endblock %}

templates/nuevousuario.html
{% extends 'base.html' %}
{% block titulo %}Nuevo usuario{% endblock %}
{% block encabezado %} 
	<h1>Registra un nuevo usuario</h1>
{% endblock %}
{% block contenido %}
	<form id='formulario' method='post' action=''>{% csrf_token %}
		<table>{{formulario}}</table>
		<p><input type='submit' value='Registrar'/></p>
	</form>
{% endblock %}

templates/perfil_cambiar_contrasena.html
{% extends 'base.html' %}

{% block titulo %}
	Cambiar contrase&ntilde;a
{% endblock %}

{% block encabezado %}
	<h1>Cambiar contrase&ntilde;a</h1>
{% endblock %}

{% block menu %}

{% endblock %}

{% block contenido %}
	<form id='formulario' method='post' action=''>
		{% csrf_token %}
		<table>{{formulario}}</table>
		<p><input class="btn btn-primary" type='submit' value='Cambiar'/></p>
	</form>
{% endblock %}

templates/responder_test.html
{% extends 'base.html' %}

{% block titulo %}
	Responder test: {{test.nombre}}
{% endblock %}

{% block encabezado %}

{% endblock %}

{% block menu %}
{% endblock %}

{% block contenido %}

	<center>
		<h1>Responder test: {{ test.test.nombre}}</h1>
		<p> Estas a punto de iniciar el test de {{ test.test.nombre }}</p>
		<p> {{ test.test.descripcion }} </p>
		<a class="btn btn-sm btn-default" href="{% url 'ptti:TestEstudiante' %}">Volver</a>
		<a class="btn btn-sm btn-primary" href="{% url 'ptti:ResponderTest' test.id test.pre_actual %}">Iniciar</a>
	</center>
{% endblock %}

templates/testAsignados.html
{% extends 'base.html' %}

{% block titulo %}
	test asignados
{% endblock %}

{% block encabezado %}
	<h1>test asignados</h1>
{% endblock %}

{% block menu %}
{% endblock %}

{% block contenido %}

<a class="btn btn-primary" href="{% url 'ptti:asignarTestEstudiante' %}">asignar test a un estudiante</a>
<a class="btn btn-primary" href="{% url 'ptti:asignarTestGrupo' %}">asignar test por grupo</a>
  {% if asignados_lista %}
	<div class="table-responsive">
		<table class="table table-striped">
      <thead>
        <tr style="font-weight:bold;text-align:center">
		    <td>estudiante</td>          
		    <td>test</td>
		    <td>estado</td>


         <td>opciones</td>
        </tr>
      </thead>
      <tbody>

		{% for asignado in asignados_lista %}
          

          	<tr style="text-align:center">
				<td>{{ asignado.estudiante }}</td>
				<td>{{ asignado.test }}</td>
				<td>{{ asignado.estado }}</td>
				<td>
				{% if asignado.estado == "FINALIZADO" %}
					<a class="btn btn-sm btn-success" href="">Diagnosticar</a>	
				{% endif %}
				{% if asignado.estado == "DIAGNOSTICADO" %}
					<a class="btn btn-sm btn-primary" href="">Modificar diagnostco</a>	
				{% endif %}
				<td><a class="btn btn-sm btn-default" href="">Ver respuestas</a></td>
				         </tr>
			

	{% endfor %}
      </tbody>
    </table>
	</div>

  {% else %}
		<div class="alert alert-danger" role="alert">
    	<p>No asignados</p>
		</div>
  {% endif %}
{% endblock %}

templates/usuarios.html
{% extends 'base.html' %}

{% block titulo %}
	Usuarios
{% endblock %}

{% block encabezado %}
	<h1>Lista de usuarios</h1>
{% endblock %}

{% block menu %}

{% endblock %}

{% block contenido %}
	<a class="btn btn-primary" href='crear'>Crear usuario</a>
  {% if usuarios_lista %}
	<div class="table-responsive">
		<table class="table table-striped">
		  <thead>
		    <tr style="font-weight:bold;text-align:center">
					<td></td>
		      <td>usuario</td>
		      <td>mail</td>
		      <td>nombre</td>
		      <td>apellido</td>
		      <td>tipo-doc</td>
					<td>num-doc</td>
					<td>fecha-nac</td>
					<td>genero</td>
					<td>direccion</td>
					<td>telefono</td>
					<!-- <td>permisos</td>-->
					<td>grupos</td>
					<td>opciones</td>
		    </tr>
		  </thead>
	    <tbody>
				{% for usuario in usuarios_lista %}
	        <tr style="text-align:center">
						<td>{{ forloop.counter }}</td>
	          <td><a href="editar/{{ usuario.id }}">{{ usuario.username }}</a></td>
						<td>{{ usuario.email }}</td>
	          <td>{{ usuario.first_name }}</td>
	          <td>{{ usuario.last_name }}</td>
						<td>{{ usuario.tipo_docto }}</td>
						<td>{{ usuario.no_docto }}</td>
						<td>{{ usuario.fecha_nac }}</td>
						<td>{{ usuario.genero }}</td>
						<td>{{ usuario.direccion }}</td>
						<td>{{ usuario.telefono }}</td>
						<!-- <td>
							admin <b>{{ usuario.is_administrador }}</b><br />
							psico <b>{{ usuario.is_psicologo }}</b><br />
							estud <b>{{ usuario.is_estudiante }}</b><br />
							activ <b>{{ usuario.is_active }}</b><br />
							super <b>{{ usuario.is_superuser }}</b><br />
						</td>-->
						<td>
						{% if usuario.is_psicologo %}
							{% for grupo in grupos_lista %}
								{% if grupo.psicologo|stringformat:"s" == usuario.username|stringformat:"s" %}
								   {{grupo.nombre}}<br/>
								{% endif %}
							{% endfor %}
						<a class="btn btn-sm btn-success" href="{% url 'ptti:asignar_psicologo_grupo' usuario.id %}">Asignar grupo</a>		
						{% else %}
							{{usuario.grupo}}
						{% endif %}
						</td>
						<td>
							<a class="btn btn-sm btn-default" href="editar/{{ usuario.id }}">editar</a>
							{% if usuario.is_active %}
								<a class="btn btn-sm btn-danger" href="desactivar/{{ usuario.id }}">desactivar</a>
							{% else %}
						    <a class="btn btn-sm btn-success" href="activar/{{ usuario.id }}">activar</a>
						  {% endif %}
						</td>

						<!-- <td>
						Grupo.objects.filter(Grupo.psicologo=usuario.username).select_related() 
							<a class="btn btn-sm btn-default" href="{% url 'ptti:editar_usuario' usuario.id %}">editar</a>
							{% if usuario.is_active %}
								<a class="btn btn-sm btn-danger" href="{% url 'ptti:desactivar_usuario' usuario.id %}">desactivar</a>
							{% else %}
						    <a class="btn btn-sm btn-success" href="{% url 'ptti:activar_usuario' usuario.id %}">activar</a>
						  {% endif %}
						</td> -->

	        </tr>
				{% endfor %}
	    </tbody>
	  </table>
	</div>

  {% else %}
		<div class="alert alert-danger" role="alert">
			<p>No usuarios</p>
		</div>

  {% endif %}
{% endblock %}